auth:
  strategy: anonymous

external_services:
  prometheus:
    url: "http://infra-monitoring-kube-prom-prometheus.monitoring.svc:9090"
  grafana:
    enabled: true
    in_cluster_url: "http://infra-monitoring-grafana.monitoring.svc"

deployment:
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
