apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-shoong-notification
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/shoong-delivery/shoong-gitops
      targetRevision: HEAD
      path: charts/shoong-app
      helm:
        valueFiles:
          - $values/envs/dev/shoong-notification.yaml
    - repoURL: https://github.com/shoong-delivery/shoong-gitops
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
