apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shoong-config
  namespace: dev
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: shoong-config
  data:
    - secretKey: NODE_ENV
      remoteRef:
        key: /shoong/dev/NODE_ENV
    - secretKey: ORDER_API_URL
      remoteRef:
        key: /shoong/dev/ORDER_API_URL
    - secretKey: KITCHEN_API_URL
      remoteRef:
        key: /shoong/dev/KITCHEN_API_URL
    - secretKey: DELIVERY_API_URL
      remoteRef:
        key: /shoong/dev/DELIVERY_API_URL
    - secretKey: NOTIFICATION_API_URL
      remoteRef:
        key: /shoong/dev/NOTIFICATION_API_URL
    - secretKey: ORDER_URL
      remoteRef:
        key: /shoong/dev/batch/ORDER_URL
