apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shoong-db-secret
  namespace: dev
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: shoong-db-secret
    template:
      data:
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .endpoint }}/shoong_dev"
  data:
    - secretKey: username
      remoteRef:
        key: /shoong/dev/db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: /shoong/dev/db-credentials
        property: password
    - secretKey: endpoint
      remoteRef:
        key: /shoong/dev/db-credentials
        property: endpoint
