replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

service:
  enabled: true      
  type: ClusterIP
  port: 3000

probe:
  enabled: true
  path: /health
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10

cronjob:
  enabled: false

env: {}

virtualService:
  enabled: false
  gateway: istio-system/shoong-gateway
  prefix: /

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"