apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
  data:
    - secretKey: admin-user
      remoteRef:
        key: /shoong/dev/grafana-admin-user
    - secretKey: admin-password
      remoteRef:
        key: /shoong/dev/grafana-admin-password
