apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
  data:
    - secretKey: slack-deploy-url
      remoteRef:
        key: /shoong/dev/slack-webhook-deploy
    - secretKey: slack-critical-url
      remoteRef:
        key: /shoong/dev/slack-webhook-critical
