apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack-webhook
  data:
    - secretKey: critical
      remoteRef:
        key: /shoong/dev/slack-webhook-critical
    - secretKey: observability
      remoteRef:
        key: /shoong/dev/slack-webhook-observability
