apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.55.0
      helm:
        valueFiles:
          - $values/infra/loki/values.yaml
          - $values/infra/loki/values-dev.yaml
    - repoURL: https://github.com/shoong-delivery/shoong-gitops
      targetRevision: troubleshoot/argocd-outofsync
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
