apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-aws-lb-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.11.0
      helm:
        valueFiles:
          - $values/infra/aws-lb-controller/values.yaml
          - $values/infra/aws-lb-controller/values-dev.yaml
    - repoURL: https://github.com/shoong-delivery/shoong-gitops
      targetRevision: troubleshoot/argocd-outofsync
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
