apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://kiali.org/helm-charts
      chart: kiali-server
      targetRevision: 2.25.0
      helm:
        valueFiles:
          - $values/infra/kiali/values-dev.yaml
    - repoURL: https://github.com/shoong-delivery/shoong-gitops
      targetRevision: troubleshoot/argocd-outofsync
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
