apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/shoong-delivery/shoong-gitops
    targetRevision: HEAD
    path: infra/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
