apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-eso-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/shoong-delivery/shoong-gitops
    targetRevision: troubleshoot/argocd-outofsync
    path: eso/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: shoong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
