apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-shoong-order
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack-deploy: ""
    notifications.argoproj.io/subscribe.on-sync-failed.slack-deploy: ""
    notifications.argoproj.io/subscribe.on-health-degraded.slack-critical: ""
spec:
  project: default
  sources:
    - repoURL: https://github.com/shoong-delivery/shoong-gitops
      targetRevision: troubleshoot/argocd-outofsync
      path: charts/shoong-app
      helm:
        valueFiles:
          - $values/envs/dev/shoong-order.yaml
    - repoURL: https://github.com/shoong-delivery/shoong-gitops
      targetRevision: troubleshoot/argocd-outofsync
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: shoong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
      - CreateNamespace=true
